//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.8922
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by wsdl, Version=2.0.50727.42.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="QueryPESELSoap11Binding", Namespace="http://dz.query.api.swd.zbp.pl")]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(BaseRequest))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(BaseResponse))]
public partial class QueryPESEL : Microsoft.Web.Services3.WebServicesClientProtocol {
    
    private System.Threading.SendOrPostCallback checkQuestionOperationCompleted;
    
    private System.Threading.SendOrPostCallback checkLimitOperationCompleted;
    
    private System.Threading.SendOrPostCallback submitQuestionOperationCompleted;
    
    /// <remarks/>
    public QueryPESEL() {
        this.Url = "https://dz3.swd.zbp.pl/broker3/services/QueryPESEL.QueryPESELHttpSoap11Endpoint/";
    }
    
    /// <remarks/>
    public event checkQuestionCompletedEventHandler checkQuestionCompleted;
    
    /// <remarks/>
    public event checkLimitCompletedEventHandler checkLimitCompleted;
    
    /// <remarks/>
    public event submitQuestionCompletedEventHandler submitQuestionCompleted;
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:checkQuestion", RequestNamespace="http://dz.query.api.swd.zbp.pl", ResponseNamespace="http://dz.query.api.swd.zbp.pl", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
    public PeselVerificationResponse checkQuestion(long systemParcelId, [System.Xml.Serialization.XmlIgnoreAttribute()] bool systemParcelIdSpecified) {
        object[] results = this.Invoke("checkQuestion", new object[] {
                    systemParcelId,
                    systemParcelIdSpecified});
        return ((PeselVerificationResponse)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BegincheckQuestion(long systemParcelId, bool systemParcelIdSpecified, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("checkQuestion", new object[] {
                    systemParcelId,
                    systemParcelIdSpecified}, callback, asyncState);
    }
    
    /// <remarks/>
    public PeselVerificationResponse EndcheckQuestion(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((PeselVerificationResponse)(results[0]));
    }
    
    /// <remarks/>
    public void checkQuestionAsync(long systemParcelId, bool systemParcelIdSpecified) {
        this.checkQuestionAsync(systemParcelId, systemParcelIdSpecified, null);
    }
    
    /// <remarks/>
    public void checkQuestionAsync(long systemParcelId, bool systemParcelIdSpecified, object userState) {
        if ((this.checkQuestionOperationCompleted == null)) {
            this.checkQuestionOperationCompleted = new System.Threading.SendOrPostCallback(this.OncheckQuestionOperationCompleted);
        }
        this.InvokeAsync("checkQuestion", new object[] {
                    systemParcelId,
                    systemParcelIdSpecified}, this.checkQuestionOperationCompleted, userState);
    }
    
    private void OncheckQuestionOperationCompleted(object arg) {
        if ((this.checkQuestionCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.checkQuestionCompleted(this, new checkQuestionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:checkLimit", RequestNamespace="http://dz.query.api.swd.zbp.pl", ResponseNamespace="http://dz.query.api.swd.zbp.pl", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
    public CheckLimitResponse checkLimit() {
        object[] results = this.Invoke("checkLimit", new object[0]);
        return ((CheckLimitResponse)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BegincheckLimit(System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("checkLimit", new object[0], callback, asyncState);
    }
    
    /// <remarks/>
    public CheckLimitResponse EndcheckLimit(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((CheckLimitResponse)(results[0]));
    }
    
    /// <remarks/>
    public void checkLimitAsync() {
        this.checkLimitAsync(null);
    }
    
    /// <remarks/>
    public void checkLimitAsync(object userState) {
        if ((this.checkLimitOperationCompleted == null)) {
            this.checkLimitOperationCompleted = new System.Threading.SendOrPostCallback(this.OncheckLimitOperationCompleted);
        }
        this.InvokeAsync("checkLimit", new object[0], this.checkLimitOperationCompleted, userState);
    }
    
    private void OncheckLimitOperationCompleted(object arg) {
        if ((this.checkLimitCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.checkLimitCompleted(this, new checkLimitCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:submitQuestion", RequestNamespace="http://dz.query.api.swd.zbp.pl", ResponseNamespace="http://dz.query.api.swd.zbp.pl", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
    public PeselVerificationResponse submitQuestion([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] PeselVerificationRequest request) {
        object[] results = this.Invoke("submitQuestion", new object[] {
                    request});
        return ((PeselVerificationResponse)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginsubmitQuestion(PeselVerificationRequest request, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("submitQuestion", new object[] {
                    request}, callback, asyncState);
    }
    
    /// <remarks/>
    public PeselVerificationResponse EndsubmitQuestion(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((PeselVerificationResponse)(results[0]));
    }
    
    /// <remarks/>
    public void submitQuestionAsync(PeselVerificationRequest request) {
        this.submitQuestionAsync(request, null);
    }
    
    /// <remarks/>
    public void submitQuestionAsync(PeselVerificationRequest request, object userState) {
        if ((this.submitQuestionOperationCompleted == null)) {
            this.submitQuestionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsubmitQuestionOperationCompleted);
        }
        this.InvokeAsync("submitQuestion", new object[] {
                    request}, this.submitQuestionOperationCompleted, userState);
    }
    
    private void OnsubmitQuestionOperationCompleted(object arg) {
        if ((this.submitQuestionCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.submitQuestionCompleted(this, new submitQuestionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    public new void CancelAsync(object userState) {
        base.CancelAsync(userState);
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://msw.api.swd.zbp.pl/xsd")]
public partial class PeselVerificationResponse : BaseResponse {
    
    private System.Nullable<bool> vDataZgonuField;
    
    private bool vDataZgonuFieldSpecified;
    
    private System.Nullable<bool> vImieDrugieField;
    
    private bool vImieDrugieFieldSpecified;
    
    private System.Nullable<bool> vKodPocztowyField;
    
    private bool vKodPocztowyFieldSpecified;
    
    private System.Nullable<bool> vMiejscowoscField;
    
    private bool vMiejscowoscFieldSpecified;
    
    private System.Nullable<bool> vNazwiskoRodoweField;
    
    private bool vNazwiskoRodoweFieldSpecified;
    
    private System.Nullable<bool> vNumerDomuField;
    
    private bool vNumerDomuFieldSpecified;
    
    private System.Nullable<bool> vNumerLokaluField;
    
    private bool vNumerLokaluFieldSpecified;
    
    private System.Nullable<bool> vUlicaField;
    
    private bool vUlicaFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<bool> vDataZgonu {
        get {
            return this.vDataZgonuField;
        }
        set {
            this.vDataZgonuField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool vDataZgonuSpecified {
        get {
            return this.vDataZgonuFieldSpecified;
        }
        set {
            this.vDataZgonuFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<bool> vImieDrugie {
        get {
            return this.vImieDrugieField;
        }
        set {
            this.vImieDrugieField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool vImieDrugieSpecified {
        get {
            return this.vImieDrugieFieldSpecified;
        }
        set {
            this.vImieDrugieFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<bool> vKodPocztowy {
        get {
            return this.vKodPocztowyField;
        }
        set {
            this.vKodPocztowyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool vKodPocztowySpecified {
        get {
            return this.vKodPocztowyFieldSpecified;
        }
        set {
            this.vKodPocztowyFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<bool> vMiejscowosc {
        get {
            return this.vMiejscowoscField;
        }
        set {
            this.vMiejscowoscField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool vMiejscowoscSpecified {
        get {
            return this.vMiejscowoscFieldSpecified;
        }
        set {
            this.vMiejscowoscFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<bool> vNazwiskoRodowe {
        get {
            return this.vNazwiskoRodoweField;
        }
        set {
            this.vNazwiskoRodoweField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool vNazwiskoRodoweSpecified {
        get {
            return this.vNazwiskoRodoweFieldSpecified;
        }
        set {
            this.vNazwiskoRodoweFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<bool> vNumerDomu {
        get {
            return this.vNumerDomuField;
        }
        set {
            this.vNumerDomuField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool vNumerDomuSpecified {
        get {
            return this.vNumerDomuFieldSpecified;
        }
        set {
            this.vNumerDomuFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<bool> vNumerLokalu {
        get {
            return this.vNumerLokaluField;
        }
        set {
            this.vNumerLokaluField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool vNumerLokaluSpecified {
        get {
            return this.vNumerLokaluFieldSpecified;
        }
        set {
            this.vNumerLokaluFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<bool> vUlica {
        get {
            return this.vUlicaField;
        }
        set {
            this.vUlicaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool vUlicaSpecified {
        get {
            return this.vUlicaFieldSpecified;
        }
        set {
            this.vUlicaFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(PeselVerificationResponse))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://msw.api.swd.zbp.pl/xsd")]
public partial class BaseResponse {
    
    private System.Nullable<bool> danePoprawneField;
    
    private bool danePoprawneFieldSpecified;
    
    private System.Nullable<long> duplicateIdField;
    
    private bool duplicateIdFieldSpecified;
    
    private string errMessageField;
    
    private System.Nullable<System.DateTime> firstStatusCheckTimeField;
    
    private bool firstStatusCheckTimeFieldSpecified;
    
    private string firstStatusCheckTimeAsStringField;
    
    private System.Nullable<System.DateTime> parcelDateField;
    
    private bool parcelDateFieldSpecified;
    
    private string parcelDateAsStringField;
    
    private System.Nullable<System.DateTime> parcelProcessDateField;
    
    private bool parcelProcessDateFieldSpecified;
    
    private string parcelProcessDateAsStringField;
    
    private string parcelStatusField;
    
    private System.Nullable<bool> raportDostepnyField;
    
    private bool raportDostepnyFieldSpecified;
    
    private System.Nullable<int> statusOperationCountField;
    
    private bool statusOperationCountFieldSpecified;
    
    private System.Nullable<long> systemParcelIdField;
    
    private bool systemParcelIdFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<bool> danePoprawne {
        get {
            return this.danePoprawneField;
        }
        set {
            this.danePoprawneField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool danePoprawneSpecified {
        get {
            return this.danePoprawneFieldSpecified;
        }
        set {
            this.danePoprawneFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<long> duplicateId {
        get {
            return this.duplicateIdField;
        }
        set {
            this.duplicateIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool duplicateIdSpecified {
        get {
            return this.duplicateIdFieldSpecified;
        }
        set {
            this.duplicateIdFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string errMessage {
        get {
            return this.errMessageField;
        }
        set {
            this.errMessageField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<System.DateTime> firstStatusCheckTime {
        get {
            return this.firstStatusCheckTimeField;
        }
        set {
            this.firstStatusCheckTimeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool firstStatusCheckTimeSpecified {
        get {
            return this.firstStatusCheckTimeFieldSpecified;
        }
        set {
            this.firstStatusCheckTimeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string firstStatusCheckTimeAsString {
        get {
            return this.firstStatusCheckTimeAsStringField;
        }
        set {
            this.firstStatusCheckTimeAsStringField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<System.DateTime> parcelDate {
        get {
            return this.parcelDateField;
        }
        set {
            this.parcelDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool parcelDateSpecified {
        get {
            return this.parcelDateFieldSpecified;
        }
        set {
            this.parcelDateFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string parcelDateAsString {
        get {
            return this.parcelDateAsStringField;
        }
        set {
            this.parcelDateAsStringField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<System.DateTime> parcelProcessDate {
        get {
            return this.parcelProcessDateField;
        }
        set {
            this.parcelProcessDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool parcelProcessDateSpecified {
        get {
            return this.parcelProcessDateFieldSpecified;
        }
        set {
            this.parcelProcessDateFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string parcelProcessDateAsString {
        get {
            return this.parcelProcessDateAsStringField;
        }
        set {
            this.parcelProcessDateAsStringField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string parcelStatus {
        get {
            return this.parcelStatusField;
        }
        set {
            this.parcelStatusField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<bool> raportDostepny {
        get {
            return this.raportDostepnyField;
        }
        set {
            this.raportDostepnyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool raportDostepnySpecified {
        get {
            return this.raportDostepnyFieldSpecified;
        }
        set {
            this.raportDostepnyFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<int> statusOperationCount {
        get {
            return this.statusOperationCountField;
        }
        set {
            this.statusOperationCountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool statusOperationCountSpecified {
        get {
            return this.statusOperationCountFieldSpecified;
        }
        set {
            this.statusOperationCountFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<long> systemParcelId {
        get {
            return this.systemParcelIdField;
        }
        set {
            this.systemParcelIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool systemParcelIdSpecified {
        get {
            return this.systemParcelIdFieldSpecified;
        }
        set {
            this.systemParcelIdFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(PeselVerificationRequest))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://msw.api.swd.zbp.pl/xsd")]
public partial class BaseRequest {
    
    private System.Nullable<int> businessUserIdField;
    
    private bool businessUserIdFieldSpecified;
    
    private string imieField;
    
    private string imieDrugieField;
    
    private System.Nullable<bool> ommitDuplicateControlField;
    
    private bool ommitDuplicateControlFieldSpecified;
    
    private string peselField;
    
    private string userQueryIdField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<int> businessUserId {
        get {
            return this.businessUserIdField;
        }
        set {
            this.businessUserIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool businessUserIdSpecified {
        get {
            return this.businessUserIdFieldSpecified;
        }
        set {
            this.businessUserIdFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string imie {
        get {
            return this.imieField;
        }
        set {
            this.imieField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string imieDrugie {
        get {
            return this.imieDrugieField;
        }
        set {
            this.imieDrugieField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<bool> ommitDuplicateControl {
        get {
            return this.ommitDuplicateControlField;
        }
        set {
            this.ommitDuplicateControlField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ommitDuplicateControlSpecified {
        get {
            return this.ommitDuplicateControlFieldSpecified;
        }
        set {
            this.ommitDuplicateControlFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string pesel {
        get {
            return this.peselField;
        }
        set {
            this.peselField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string userQueryId {
        get {
            return this.userQueryIdField;
        }
        set {
            this.userQueryIdField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://msw.api.swd.zbp.pl/xsd")]
public partial class PeselVerificationRequest : BaseRequest {
    
    private string dataZgonuField;
    
    private string kodPocztowyField;
    
    private string miejscowoscField;
    
    private string nazwiskoField;
    
    private string nazwiskoRodoweField;
    
    private string numerDomuField;
    
    private string numerLokaluField;
    
    private string ulicaField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string dataZgonu {
        get {
            return this.dataZgonuField;
        }
        set {
            this.dataZgonuField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string kodPocztowy {
        get {
            return this.kodPocztowyField;
        }
        set {
            this.kodPocztowyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string miejscowosc {
        get {
            return this.miejscowoscField;
        }
        set {
            this.miejscowoscField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string nazwisko {
        get {
            return this.nazwiskoField;
        }
        set {
            this.nazwiskoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string nazwiskoRodowe {
        get {
            return this.nazwiskoRodoweField;
        }
        set {
            this.nazwiskoRodoweField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string numerDomu {
        get {
            return this.numerDomuField;
        }
        set {
            this.numerDomuField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string numerLokalu {
        get {
            return this.numerLokaluField;
        }
        set {
            this.numerLokaluField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string ulica {
        get {
            return this.ulicaField;
        }
        set {
            this.ulicaField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://msw.api.swd.zbp.pl/xsd")]
public partial class CheckLimitResponse {
    
    private System.Nullable<int> actualDayUsageField;
    
    private bool actualDayUsageFieldSpecified;
    
    private System.Nullable<int> actualMonthUsageField;
    
    private bool actualMonthUsageFieldSpecified;
    
    private string currentDayField;
    
    private string currentMonthField;
    
    private System.Nullable<int> dayHardLimitField;
    
    private bool dayHardLimitFieldSpecified;
    
    private System.Nullable<int> daySoftLimitField;
    
    private bool daySoftLimitFieldSpecified;
    
    private System.Nullable<int> monthHardLimitField;
    
    private bool monthHardLimitFieldSpecified;
    
    private System.Nullable<int> monthSoftLimitField;
    
    private bool monthSoftLimitFieldSpecified;
    
    private string registerField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<int> actualDayUsage {
        get {
            return this.actualDayUsageField;
        }
        set {
            this.actualDayUsageField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool actualDayUsageSpecified {
        get {
            return this.actualDayUsageFieldSpecified;
        }
        set {
            this.actualDayUsageFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<int> actualMonthUsage {
        get {
            return this.actualMonthUsageField;
        }
        set {
            this.actualMonthUsageField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool actualMonthUsageSpecified {
        get {
            return this.actualMonthUsageFieldSpecified;
        }
        set {
            this.actualMonthUsageFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string currentDay {
        get {
            return this.currentDayField;
        }
        set {
            this.currentDayField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string currentMonth {
        get {
            return this.currentMonthField;
        }
        set {
            this.currentMonthField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<int> dayHardLimit {
        get {
            return this.dayHardLimitField;
        }
        set {
            this.dayHardLimitField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool dayHardLimitSpecified {
        get {
            return this.dayHardLimitFieldSpecified;
        }
        set {
            this.dayHardLimitFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<int> daySoftLimit {
        get {
            return this.daySoftLimitField;
        }
        set {
            this.daySoftLimitField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool daySoftLimitSpecified {
        get {
            return this.daySoftLimitFieldSpecified;
        }
        set {
            this.daySoftLimitFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<int> monthHardLimit {
        get {
            return this.monthHardLimitField;
        }
        set {
            this.monthHardLimitField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool monthHardLimitSpecified {
        get {
            return this.monthHardLimitFieldSpecified;
        }
        set {
            this.monthHardLimitFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<int> monthSoftLimit {
        get {
            return this.monthSoftLimitField;
        }
        set {
            this.monthSoftLimitField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool monthSoftLimitSpecified {
        get {
            return this.monthSoftLimitFieldSpecified;
        }
        set {
            this.monthSoftLimitFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string register {
        get {
            return this.registerField;
        }
        set {
            this.registerField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
public delegate void checkQuestionCompletedEventHandler(object sender, checkQuestionCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class checkQuestionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal checkQuestionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public PeselVerificationResponse Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((PeselVerificationResponse)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
public delegate void checkLimitCompletedEventHandler(object sender, checkLimitCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class checkLimitCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal checkLimitCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public CheckLimitResponse Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((CheckLimitResponse)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
public delegate void submitQuestionCompletedEventHandler(object sender, submitQuestionCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class submitQuestionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal submitQuestionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public PeselVerificationResponse Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((PeselVerificationResponse)(this.results[0]));
        }
    }
}
